repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.31.0
    hooks:
      - id: yapf
        additional_dependencies: ['toml']
      
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./.venv/bin/pytest tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true